name: "Test Coverage Report"
on:
  pull_request_target:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          custom-title: Test coverage report (Jest)
          output: report-markdown, comment
